PRAGMA foreign_keys = ON;

-- people: playerID is primary key
CREATE TABLE IF NOT EXISTS people (
  ID INTEGER,
  playerID TEXT PRIMARY KEY,
  birthYear INTEGER,
  birthMonth INTEGER,
  birthDay INTEGER,
  birthCity TEXT,
  birthCountry TEXT,
  birthState TEXT,
  deathYear INTEGER,
  deathMonth INTEGER,
  deathDay INTEGER,
  deathCountry TEXT,
  deathState TEXT,
  deathCity TEXT,
  nameFirst TEXT,
  nameLast TEXT,
  nameGiven TEXT,
  weight INTEGER,
  height INTEGER,
  bats TEXT,
  throws TEXT,
  debut TEXT,
  bbrefID TEXT,
  finalGame TEXT,
  retroID TEXT
);

-- teams: composite primary key (teamID, yearID)
CREATE TABLE IF NOT EXISTS teams (
  yearID INTEGER,
  lgID TEXT,
  teamID TEXT,
  franchID TEXT,
  divID TEXT,
  Rank INTEGER,
  G INTEGER,
  Ghome INTEGER,
  W INTEGER,
  L INTEGER,
  DivWin TEXT,
  WCWin TEXT,
  LgWin TEXT,
  WSWin TEXT,
  R INTEGER,
  AB INTEGER,
  H INTEGER,
  "2B" INTEGER,
  "3B" INTEGER,
  HR INTEGER,
  BB INTEGER,
  SO INTEGER,
  SB INTEGER,
  CS INTEGER,
  HBP INTEGER,
  SF INTEGER,
  RA INTEGER,
  ER INTEGER,
  ERA REAL,
  CG INTEGER,
  SHO INTEGER,
  SV INTEGER,
  IPouts INTEGER,
  HA INTEGER,
  HRA INTEGER,
  BBA INTEGER,
  SOA INTEGER,
  E INTEGER,
  DP INTEGER,
  FP REAL,
  name TEXT,
  park TEXT,
  attendance INTEGER,
  BPF INTEGER,
  PPF INTEGER,
  teamIDBR TEXT,
  teamIDlahman45 TEXT,
  teamIDretro TEXT,
  PRIMARY KEY (teamID, yearID)
);

-- batting: composite primary key (playerID, yearID, stint)
-- foreign key (playerID) -> people(playerID)
-- foreign key (teamID, yearID) -> teams(teamID, yearID)
CREATE TABLE IF NOT EXISTS batting (
  playerID TEXT,
  yearID INTEGER,
  stint INTEGER,
  teamID TEXT,
  lgID TEXT,
  G INTEGER,
  AB INTEGER,
  R INTEGER,
  H INTEGER,
  "2B" INTEGER,
  "3B" INTEGER,
  HR INTEGER,
  RBI INTEGER,
  SB INTEGER,
  CS INTEGER,
  BB INTEGER,
  SO INTEGER,
  IBB INTEGER,
  HBP INTEGER,
  SH INTEGER,
  SF INTEGER,
  GIDP INTEGER,
  PRIMARY KEY (playerID, yearID, stint),
  FOREIGN KEY (playerID) REFERENCES people(playerID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (teamID, yearID) REFERENCES teams(teamID, yearID) ON DELETE RESTRICT ON UPDATE CASCADE
);
